
services:

#  app:
#    image: storage-files:latest
#    container_name: app
#    restart: always
#    depends_on:
#      - postgres
#      - minio
#      - redis
#    environment:
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#    ports:
#      - "8090:8090

  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_storage
    ports:
      - "5442:5432"
    volumes:
      - postgres-data:/data

  minio:
    image: minio/minio:latest
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  minio_data:
  redis-data:
  postgres-data: