spring:

#  datasource:
#
##    url: jdbc:postgresql://localhost:5442/cloud_storage
##    url: "${SPRING_DATASOURCE_URL}"
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver


  session:
    store-type: redis



  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true

