spring:

  data:
    redis:
      host: localhost
      port: 6379


  datasource:
    url: jdbc:postgresql://localhost:5442/cloud_storage
    username: db_user
    password: password
    driver-class-name: org.postgresql.Driver

minio:
  bucket: user-files
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin