spring:

  session:
    store-type: redis

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true